### ISSUE TITLE
デプロイ後の設定で、データベースの利用方法につまづいている

### ISSUE THREAD

**Issue by yosuke-43** [yosuke-43/dog_app#63]
- 質問内容・実現したいこと
fly.ioを使用して、デプロイまで完了しました。
開発用データベースで登録していたデータを、本番用データベースでも使用したいためデータの移行が行いたいです。

- 現状発生している問題・エラーメッセージ
fly.io上にデータベースを作成したのですが、postgreSQLにも接続できず、データの移行もできていない状況です。
なにが原因か特定できていない状況です。

- どの処理までうまく動いているのか
fly.io上でpostgresでデータベースの作成までは完了しています。
↑これの根拠は下記のfly launchをした際に下記の内容を確認しました。
```
Postgres cluster dog-app-db created
  Username:    postgres
  Password:    FCGFcBEDWqgjrBm
  Hostname:    dog-app-db.internal
  Flycast:     fdaa:6:b74b:0:1::2
  Proxy port:  5432
  Postgres port:  5433
  Connection string: postgres://postgres:FCGFcBEDWqgjrBm@dog-app-db.flycast:5432

```
また、fly.ioのアプリ上からもデータベースが作成されていることは確認しています。
[![Image from Gyazo](https://i.gyazo.com/7968f02a9a49582efad5fc4af3449ee4.png)](https://gyazo.com/7968f02a9a49582efad5fc4af3449ee4)
[![Image from Gyazo](https://i.gyazo.com/6d22a8f540d76ae4bf744e778a85a4e9.png)](https://gyazo.com/6d22a8f540d76ae4bf744e778a85a4e9)

- 該当のソースコード
データの移行以前にそもそもpostgreSQLに接続できるかを調べました。
postgreSQLに接続できるかの確認をしたときのコマンド
```
yosuketokito@tokitouyousukenoMacBook-Air dog_app % psql -h dog-app-db.internal -p 5433 -U postgres -d dog_app
psql: error: could not translate host name "dog-app-db.internal" to address: nodename nor servname provided, or not known

```

- エラーから考えられる原因
digコマンドを試してみた結果
```
yosuketokito@tokitouyousukenoMacBook-Air dog_app % dig dog-app-db.fly.dev


; <<>> DiG 9.10.6 <<>> dog-app-db.fly.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42443
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;dog-app-db.fly.dev.            IN      A

;; AUTHORITY SECTION:
fly.dev.                300     IN      SOA     ns1.flydns.net. ops.fly.io. 1708314580 86400 7200 604800 300

;; Query time: 30 msec
;; SERVER: 2001:a7ff:5f01::a#53(2001:a7ff:5f01::a)
;; WHEN: Mon Feb 19 12:51:07 JST 2024
;; MSG SIZE  rcvd: 107

```

```
yosuketokito@tokitouyousukenoMacBook-Air dog_app % dig dog-app-db.internal

; <<>> DiG 9.10.6 <<>> dog-app-db.internal
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 28552
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;dog-app-db.internal.           IN      A

;; AUTHORITY SECTION:
.                       86400   IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2024021801 1800 900 604800 86400

;; Query time: 19 msec
;; SERVER: 2001:a7ff:5f01::a#53(2001:a7ff:5f01::a)
;; WHEN: Mon Feb 19 13:02:01 JST 2024
;; MSG SIZE  rcvd: 123

```

```
yosuketokito@tokitouyousukenoMacBook-Air dog_app % psql "host=fdaa:6:b74b:0:1::2 port=5433 user=postgres dbname=dog-app-db sslmode=require"

psql: error: connection to server at "fdaa:6:b74b:0:1::2", port 5433 failed: Operation timed out
        Is the server running on that host and accepting TCP/IP connections?

```

- 試したこと
config/database.ymlファイルを以下に書き直してもう一度デプロイコマンドをした
```
production:
  adapter: postgresql
  encoding: unicode
  database: dog-app-db  # データベース名を指定
  username: postgres  # ユーザー名を指定
  password: FCGFcBEDWqgjrBm  # パスワードを指定
  host: dog-app-db.internal  # ホスト名を指定
  port: 5433  # ポート番号を指定
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

```

**Comment by kerochelo** [comment]
@yosuke-43 
flyioのdb情報貼っていますかね？
postgresqlはデフォルトのポートが5432なので、その部分を再度確認していただいてもよろしいでしょうか？

**Comment by kerochelo** [comment]
あとflyioの環境変数を利用してpasswordは隠すようにしましょう！

**Comment by yosuke-43** [comment]
@kerochelo 

> flyioのdb情報はあっていますかね？
最初にfly launchをした際のメモを残していたので、これで合ってると思います。
```
Postgres cluster dog-app-db created
  Username:    postgres
  Password:    FCGFcBEDWqgjrBm
  Hostname:    dog-app-db.internal
  Flycast:     fdaa:6:b74b:0:1::2
  Proxy port:  5432
  Postgres port:  5433
  Connection string: postgres://postgres:FCGFcBEDWqgjrBm@dog-app-db.flycast:5432
```


> postgresqlはデフォルトのポートが5432なので、その部分を再度確認していただいてもよろしいでしょうか？
```
yosuketokito@tokitouyousukenoMacBook-Air dog_app % psql -h dog-app-db.internal -p 5432 -U postgres -d postgres

psql: error: could not translate host name "dog-app-db.internal" to address: nodename nor servname provided, or not known
```
5432に変更しても接続はできなかったです。

また、fly.ioのダッシュボードをもとに
[![Image from Gyazo](https://i.gyazo.com/1a4113ac6295bab669b9c2f7001633b5.png)](https://gyazo.com/1a4113ac6295bab669b9c2f7001633b5)
下記のコマンドを実施しましたが、データベースに接続はできませんでした。
```
yosuketokito@tokitouyousukenoMacBook-Air dog_app % psql -h fdaa:6:b74b:0:1::2 -p 5432 -U postgres -d postgres

psql: error: connection to server at "fdaa:6:b74b:0:1::2", port 5432 failed: Operation timed out

```


> あとflyioの環境変数を利用してpasswordは隠すようにしましょう！
config/database.yml
```
production:
  adapter: postgresql
  encoding: unicode
  database: dog-app-db  # データベース名を指定
  username: postgres  # ユーザー名を指定
  password: ENV['SECRET_KEY']  # パスワードを指定
  host: dog-app-db.internal  # ホスト名を指定
  port: 5432  # ポート番号を指定
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

```
編集しました
